:books: translate chapter 3 B+tree Indexes
yakst/unofficialmysqlguide-ja pull request #29
Opened 2017-03-01 12:45 UTC by takaidohigasi

2017-03-01 14:23 UTC, takaidohigasi commented
重複しますが下記ご活用ください
https://app.classeur.io/#!/files/F7fHDvGtWDZaZUSJaP1U

2017-03-01 23:07 UTC, takaidohigasi commented
「通常」がことばとしてうるさいのと場所が悪いのを修正予定

2017-03-04 09:08 UTC, takaidohigasi commented
日本語の表現を若干改善しました

2017-03-04 12:49 UTC, doublemarket requested changes
長音符について1箇所だけ指摘しましたが、「オプティマイザ」を長音符なしにするなら、クエリ、スケーラビリティ、なども長音符なしで統一してしまった方がいいかもしれませんね。。

2017-03-04 12:49 UTC, doublemarket commented on _posts/2017-02-28-introduction.md
> -クエリオプティマイザーはクエリを「入力」とみなし、この章に記述したプロセスを経て実行計画を「出力」として生成します。私はよく、クエリー最適化をGPSのナビゲーションと対比して例えます。
「クエリ」と「クエリー」が混在しているのは統一した方が良さそうですね。

2017-03-04 12:49 UTC, doublemarket commented on _posts/2017-03-01-B+tree-indexes.md
> +上記のダイアグラムはルートインデックスページは25のインデックスページへのポインタを保持しており、このインデックスページ自体は平均で1538のリーフページヘのポインタをもっています。829813への経路は図上でハイライトされておりこれは次のとおりです。
ダイアグラムは単に図としてしまった方がいい気がします(図上、としたりしているので)。

2017-03-04 12:49 UTC, doublemarket commented on _posts/2017-03-01-B+tree-indexes.md
> +20ホップするということは少ないとはいえない20回のディスクアクセスを発生させることとなり、この点からBツリーは性能上劣っています。小規模な複数のIOアクセスは比較的高コスト[^1]なのです。これに比べ、同じ検索をB+ツリー[^2]でおこなうと**わずか2ホップ**でよくなります。
"20 hops is actually a high number if it also results in 20 disk accesses"は、「20ホップがそのまま20回のディスクアクセスを発生させる場合、少ない回数とは言えなくなります」とかどうでしょうか。「少ないとは言えない20回のディスクアクセス」だとちょっと原文のニュアンスから離れてしまう気がします。

2017-03-05 11:55 UTC, takaidohigasi commented on _posts/2017-02-28-introduction.md
> -クエリオプティマイザーはクエリを「入力」とみなし、この章に記述したプロセスを経て実行計画を「出力」として生成します。私はよく、クエリー最適化をGPSのナビゲーションと対比して例えます。
こちらはクエリーに統一します。
https://gist.github.com/takaidohigasi/b5774f65e6403650dba3

2017-03-10 23:30 UTC, takaidohigasi commented on _posts/2017-02-28-introduction.md
> -クエリオプティマイザーはクエリを「入力」とみなし、この章に記述したプロセスを経て実行計画を「出力」として生成します。私はよく、クエリー最適化をGPSのナビゲーションと対比して例えます。
スケーラビリティーについても確認しましたが長音ありが原則のようです。
https://dev.mysql.com/doc/search/?d=171&p=1&q=%E3%82%B9%E3%82%B1%E3%83%BC%E3%83%A9%E3%83%93%E3%83%AA%E3%83%86%E3%82%A3

したがって翻訳揺れメモの通り

- 基本は長音記号をつける
- 「オプティマイザ」については例外的に公式ドキュメントに倣い長音記号をつけない

としたいと思いますがよろしいでしょうか

2017-03-10 23:48 UTC, takaidohigasi commented on _posts/2017-03-01-B+tree-indexes.md
> +20ホップするということは少ないとはいえない20回のディスクアクセスを発生させることとなり、この点からBツリーは性能上劣っています。小規模な複数のIOアクセスは比較的高コスト[^1]なのです。これに比べ、同じ検索をB+ツリー[^2]でおこなうと**わずか2ホップ**でよくなります。
コメントありがとうございます、長考してます。

> Where I would say a Binary tree is limited, is that 20 hops is actually a high number if it also results in 20 disk accesses. It also does not mitigate that very small IO accesses are relatively expensive [1] . By comparison, here is the same search in a B+tree [2] which uses only 2 hops:

2017-03-10 23:58 UTC, takaidohigasi commented on _posts/2017-03-01-B+tree-indexes.md
> +20ホップするということは少ないとはいえない20回のディスクアクセスを発生させることとなり、この点からBツリーは性能上劣っています。小規模な複数のIOアクセスは比較的高コスト[^1]なのです。これに比べ、同じ検索をB+ツリー[^2]でおこなうと**わずか2ホップ**でよくなります。
ご指摘の通りですので修正します!

2017-03-11 07:46 UTC, doublemarket approved these changes
1点だけコメントしましたが、とても良い訳だと思います！

2017-03-11 07:46 UTC, doublemarket commented on _posts/2017-03-01-B+tree-indexes.md
> +[^2]: InnoDBのB+ツリーで分析される実際の値を表示は https://github.com/jeremycole/innodb_ruby で実施
実際の値を表示は→実際の値**の**表示は
の方が良さそうです。

2017-03-11 09:50 UTC, takaidohigasi commented on _posts/2017-03-01-B+tree-indexes.md
> +[^2]: InnoDBのB+ツリーで分析される実際の値を表示は https://github.com/jeremycole/innodb_ruby で実施
こちら修正します！

2017-03-11 09:55 UTC, takaidohigasi commented on _posts/2017-03-01-B+tree-indexes.md
> +[^2]: InnoDBのB+ツリーで分析される実際の値の表示は https://github.com/jeremycole/innodb_ruby で実施
こちら修正いたしました

2017-03-13 23:22 UTC, merged