[WIP]:books: translate chapter 5. Optimizer Trace
yakst/unofficialmysqlguide-ja pull request #32
Opened 2017-03-11 07:48 UTC by takaidohigasi

2017-03-11 11:15 UTC, takaidohigasi commented on _posts/2017-03-09-optimizer-trace.md
> +      "p"                      # インデックスが利用可能と判断しているにもかかわらずである!
ですますがしっくりかけなかったので、ここだけ「である」で書きました。何かいい感じに書けそうであればコメント下さい！

2017-03-13 13:54 UTC, doublemarket requested changes

2017-03-13 13:54 UTC, doublemarket commented on _posts/2017-03-09-optimizer-trace.md
> +* 代替選択肢が適切でなかったのか？(例えば、ある実行は特定のユースケースのみに利用できる、など)
「ある実行」は「ある最適化(some optimization)」の方が意味も通るし訳としても近いと思います。

2017-03-13 13:54 UTC, doublemarket commented on _posts/2017-03-09-optimizer-trace.md
> +* 代替選択肢が適切でなかったのか？(例えば、ある実行は特定のユースケースのみに利用できる、など)
これは私の好みなので無理に合わせる必要はないですが、「代替選択肢」よりは「代わりの選択肢」あるいはもっとくだけて意訳して「選ばれなかった実行計画」の方がスッと入る気がします。

2017-03-13 13:54 UTC, doublemarket commented on _posts/2017-03-09-optimizer-trace.md
> +      "p"                      # インデックスが利用可能と判断しているにもかかわらずである!
私も第4章でこのコメントはだである調にしたので、いいと思います(なんかコメントはですますだとちょっとやりにくいですね)。「判断しているにもかかわらずである！」はだである調というよりむしろ偉い人が宣言してる風なので(笑)、「判断しているのに！」とかでもいい気がしました。

2017-03-13 13:54 UTC, doublemarket commented on _posts/2017-03-09-optimizer-trace.md
> +例2では、インデックスp(Population, 人口)がテーブルに追加された後であるにもかかわらず、選択されていないことがわかります。`EXPLAIN`からこれが候補であったことはわかりますが、なぜ選択されなかったかはわかりません。この理由を知るためには、`OPTIMIZER_TRACE`を利用する必要があります。
原文でPopulationのPが大文字なのでちょっと分かりにくいですが、かっこも含めてインラインコードになっているので、かっこ内はPopulationのPを取ってインデックスpと言っているのではなく、`p (population)`というインデックスの定義を書いているというように私は受け取りました。そう考えると、かっこ内に「人口」と書くのはちょっと違う気がしますがどうでしょうか。

2017-03-13 13:54 UTC, doublemarket commented on _posts/2017-03-09-optimizer-trace.md
> +                     "cause": "cost"             # テーブルスキャンよりコストがかかるからである!
前のSQL内のコメントで指摘した点を反映するならここも合わせてお願いします。

2017-03-13 13:54 UTC, doublemarket commented on _posts/2017-03-09-optimizer-trace.md
> +例3の`range_scan_alternatives` ではp(Population, 人口)は考慮されている一方で、コストに基いて選択肢から除外(`"chosen": false and "cause": "cost"`)されたことを示しています。出力にはインデックスを利用する場合のコスト見積もりも表示されており、130.61コスト単位とあります。これがテーブルスキャンの場合の55.9コスト
例2での`p (population)`の指摘を適用するなら、こちらもお願いします。

2017-03-13 13:54 UTC, doublemarket commented on _posts/2017-03-09-optimizer-trace.md
> +なぜこのようになるかを説明するには、インデックスはやることを減らす必要があることを理解する必要があります。このデータセットの大多数の国の人口は500万人以上となります。オプティマイザがインデックスとデータを行ったりきたりするより、テーブルスキャンしたほうが速いと判断したことになります。上級ユーザーの方々は、この意思決定を行うためのコストを調整することができます。
「インデックスはやることを減らす必要」は「インデックス**が**やることを減らす必要」の方が自然ではないでしょうか。

2017-03-13 14:36 UTC, takaidohigasi commented on _posts/2017-03-09-optimizer-trace.md
> +      "p"                      # インデックスが利用可能と判断しているにもかかわらずである!
>「判断しているのに！」

うまい...!いい案ありがとうございます。

2017-03-13 14:37 UTC, takaidohigasi commented on _posts/2017-03-09-optimizer-trace.md
> +* 代替選択肢が適切でなかったのか？(例えば、ある実行は特定のユースケースのみに利用できる、など)
「代わりの選択肢」にしてみます、ありがとうございます！

2017-03-13 14:38 UTC, takaidohigasi commented on _posts/2017-03-09-optimizer-trace.md
> +* 代替選択肢が適切でなかったのか？(例えば、ある実行は特定のユースケースのみに利用できる、など)
コメントありがとうございます、原文もう一度確認してみます...!

2017-03-13 15:02 UTC, takaidohigasi commented on _posts/2017-03-09-optimizer-trace.md
> +例2では、インデックスp(Population, 人口)がテーブルに追加された後であるにもかかわらず、選択されていないことがわかります。`EXPLAIN`からこれが候補であったことはわかりますが、なぜ選択されなかったかはわかりません。この理由を知るためには、`OPTIMIZER_TRACE`を利用する必要があります。
これは鋭いご指摘...

p(population)に修正します。

2017-03-13 15:03 UTC, takaidohigasi commented on _posts/2017-03-09-optimizer-trace.md
> +なぜこのようになるかを説明するには、インデックスはやることを減らす必要があることを理解する必要があります。このデータセットの大多数の国の人口は500万人以上となります。オプティマイザがインデックスとデータを行ったりきたりするより、テーブルスキャンしたほうが速いと判断したことになります。上級ユーザーの方々は、この意思決定を行うためのコストを調整することができます。
ここの日本語は少し考えさせてください！確かに自然ではないです...!

2017-03-14 00:08 UTC, takaidohigasi commented on _posts/2017-03-09-optimizer-trace.md
> +* 代替選択肢が適切でなかったのか？(例えば、ある実行は特定のユースケースのみに利用できる、など)
何回か読み返したら「選ばれなかった実行計画」が一番良かったです...!ありがとうございます

2017-03-14 01:01 UTC, takaidohigasi commented on _posts/2017-03-09-optimizer-trace.md
> +なぜこのようになるかを説明するには、インデックスはやることを減らす必要があることを理解する必要があります。このデータセットの大多数の国の人口は500万人以上となります。オプティマイザがインデックスとデータを行ったりきたりするより、テーブルスキャンしたほうが速いと判断したことになります。上級ユーザーの方々は、この意思決定を行うためのコストを調整することができます。
`インデックスにはやることが多くこれを減らす必要がある` このように修正します

2017-03-14 01:26 UTC, doublemarket approved these changes
いぇいいぇい！ ありがとうございます！

2017-03-14 09:32 UTC, takaidohigasi commented
ありがとうございます。こちらも明日公開予定です！

2017-03-15 09:15 UTC, merged