:books: translate chapter 7. cost based optimization
yakst/unofficialmysqlguide-ja pull request #37
Opened 2017-03-13 14:57 UTC by takaidohigasi

WIP

2017-03-14 08:24 UTC, takaidohigasi commented on _layouts/default.html
> +    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" media="screen">
先に定義したためクラスなどが重複するものは従来通りあとから読まれたものが優先される

2017-03-14 09:33 UTC, takaidohigasi commented
度々すみません...っ!!

2017-03-18 09:16 UTC, doublemarket requested changes
遅くなりましたがレビューしましたー

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +上記が単純化であると述べたのは、オプティマイザは可能性のあるそれぞれの実行計画を徹底的に検索するわけではないからです。例えば、5つのテーブルが結合される場合、各テーブルに5つのインデックスがあるとすると、`5! * 5! =14400` 「を超える」クエリーの実行パターンがあることになります。
確かにoverは「を超える」かもしれませんが、日本語としてはちょっとかぎかっこの括り方に違和感があるので「超える」でいい気がします。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +* 各インデックスは1つ以上アクセス方法があります(例えば、インデックススキャン、レンジスキャンやインデックスルックアップです）。その上、各テーブルがテーブルスキャンを利用する可能性もあります。
かっこの始まりが半角で終わりが全角なのが気になってしまう私は細かすぎる！？

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +コスト自体はリソース利用量を表す論理的な単位です。1単位にもはや正確な意味はありませんが、起源としては1990年代のハードディスクの1回のランダムIOと遡れます。
元々はそういう意味だったのか。。！(すいませんレビューと関係ないですw)

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include warning.html warn="コスト係数を修正すると多くのクエリーの計画は「悪くなる」可能性があることにご注意ください！ほとんどのプロダクション環境ではクエリーヒントを追加するのがよいでしょう。" %}
プロダクション環境、でも問題はない気がしますが、本番環境、の方がより一般的な気もします。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include warning.html warn="次のエグザンプルに進む前に忘れずにコストを初期化するようにしてください。<br /><br />UPDATE mysql.server_cost SET cost_value=NULL WHERE cost_name='row_evaluate_cost';<br />
エグザンプル、は単に例で良いと思います(次の項で「例3で」と言っている)。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +
ここに入るはずの「Example 4 shows...」から始まる段落の訳が抜けている気がします。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +## メターデータと統計
メターデータ -> メタデータ

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +| 概要 | ディクショナリはテーブル毎にインデックスの一覧の情報を持ちます | インデックスがユニークの場合、永久変換に利用され、実行計画のある部分を短縮するのに利用されます | オプティマイザはnullの可能性がある値を正しく扱う必要があります。列のNullabilityは一部の実行計画に影響を与えます |
nullabilityって確かに英単語としてはありますが、「列がnullになり得るかどうか」といったように訳してしまった方が分かりやすいのではないでしょうか。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +| 手動更新 | ANALYZE TABLE | ANALYZE TABLE | N/A |
ANALYZE TABLEはコマンドなので`ANALYZE TABLE`とした方がいいかもです。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +| 自動更新 | 通常オペレーション[^3]中 | テーブルの10%に変更が発生したとき| N/A |
N/Aは日本語の表ではあまり馴染みがないので、「-」で済ますか「適用なし」などとしてみたらどうでしょうか。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +| 通常の利用 | テーブルスキャンコストの決定に利用。インデックスがない場合の結合順に利用(大きいテーブルから先に) | 結合順の決定に利用。レンジの見積もりが最大インデックスダイブ数を超えた場合にも利用される | 述部の評価に利用。(利用可能なインデックスから何行マッチするかを推定)。population > 5000000がインデックスを使うべきでないかどうかを決めるのに利用する |
commonly used forは少し意訳して「使用頻度」とするのはどうでしょう。commonlyを通常と訳してしまうといまいちなんのことなのか分からないのではと思います。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include info.html info="統計を利用することで、品質見積もり時と商用環境で同じようにみえるクエリーが全く異なった実行となることがあります。クエリーの計画はデータ分布が変わるにつれて変化する可能性もあります" %}
in QA and productionは「品質保証のための環境と本番環境で」としてみてはどうでしょう。あるいは品質保証のための環境というより思い切ってステージング環境と書いてしまった方が、一般的なワークフローと合致して読者からすると分かりやすい気がします。

2017-03-18 09:16 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include info.html info="統計を利用することで、品質見積もり時と商用環境で同じようにみえるクエリーが全く異なった実行となることがあります。クエリーの計画はデータ分布が変わるにつれて変化する可能性もあります" %}
2つ目の文に「in production」の訳が含まれていないので、前の文との繋がりが少し分かりにくくなっていますね。「本番環境だと」とか文頭に入れた方がよさそうです。

2017-03-20 00:13 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +上記が単純化であると述べたのは、オプティマイザは可能性のあるそれぞれの実行計画を徹底的に検索するわけではないからです。例えば、5つのテーブルが結合される場合、各テーブルに5つのインデックスがあるとすると、`5! * 5! =14400` 「を超える」クエリーの実行パターンがあることになります。
ありがとうございます。そのように修正します！

2017-03-20 00:13 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +* 各インデックスは1つ以上アクセス方法があります(例えば、インデックススキャン、レンジスキャンやインデックスルックアップです）。その上、各テーブルがテーブルスキャンを利用する可能性もあります。
気がついてませんでした... 確認して修正します

2017-03-20 00:14 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +
oh... sorry

2017-03-20 00:14 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include warning.html warn="コスト係数を修正すると多くのクエリーの計画は「悪くなる」可能性があることにご注意ください！ほとんどのプロダクション環境ではクエリーヒントを追加するのがよいでしょう。" %}
プロダクション環境/商用環境/本番環境 → 本番環境としたいと思います！

2017-03-20 00:14 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include warning.html warn="次のエグザンプルに進む前に忘れずにコストを初期化するようにしてください。<br /><br />UPDATE mysql.server_cost SET cost_value=NULL WHERE cost_name='row_evaluate_cost';<br />
Yes!

2017-03-20 00:15 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +## メターデータと統計
失礼しました... ありがとうございます、修正します

2017-03-20 00:17 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +| 概要 | ディクショナリはテーブル毎にインデックスの一覧の情報を持ちます | インデックスがユニークの場合、永久変換に利用され、実行計画のある部分を短縮するのに利用されます | オプティマイザはnullの可能性がある値を正しく扱う必要があります。列のNullabilityは一部の実行計画に影響を与えます |
そのようにします。
表のタイトルについてはNullabilityで残して表中の説明をNullability(列がnullになりうるかどうか)としたいと思います。

2017-03-20 00:17 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +| 自動更新 | 通常オペレーション[^3]中 | テーブルの10%に変更が発生したとき| N/A |
そうかもしれません、

「-」にします

2017-03-20 00:18 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +| 手動更新 | ANALYZE TABLE | ANALYZE TABLE | N/A |
直してみます。表中のバッククォートがそのまま表示されてしまうようであればそのままにします。

2017-03-20 00:23 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +| 通常の利用 | テーブルスキャンコストの決定に利用。インデックスがない場合の結合順に利用(大きいテーブルから先に) | 結合順の決定に利用。レンジの見積もりが最大インデックスダイブ数を超えた場合にも利用される | 述部の評価に利用。(利用可能なインデックスから何行マッチするかを推定)。population > 5000000がインデックスを使うべきでないかどうかを決めるのに利用する |
ありがとうございます。

頻度とは少し違うように思います。

「一般的な使われ方」でどうでしょう

2017-03-20 00:27 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include info.html info="統計を利用することで、品質見積もり時と商用環境で同じようにみえるクエリーが全く異なった実行となることがあります。クエリーの計画はデータ分布が変わるにつれて変化する可能性もあります" %}
ありがとうございます。ちょっと考えてます！！

2017-03-20 02:56 UTC, doublemarket commented on _posts/2017-03-14-cost-based-optimization.md
> +| 通常の利用 | テーブルスキャンコストの決定に利用。インデックスがない場合の結合順に利用(大きいテーブルから先に) | 結合順の決定に利用。レンジの見積もりが最大インデックスダイブ数を超えた場合にも利用される | 述部の評価に利用。(利用可能なインデックスから何行マッチするかを推定)。population > 5000000がインデックスを使うべきでないかどうかを決めるのに利用する |
あー、もう一度表を読み直して、そもそも表の意味自体を読み違えていたことに気づきました。一番左の列は、統計情報の特質を表しているのですね。となると、一般的な使われ方、がしっくりきますね。

読み違えに気づいて思ったのですが、例えば

- 計算 -> 計算のタイミング
- 自動更新 -> 自動更新のタイミング
- 手動更新 -> 手動更新の方法

などと左の列の記述を変えた方がより表として分かりやすくなりそうですね。

2017-03-20 08:26 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +| 通常の利用 | テーブルスキャンコストの決定に利用。インデックスがない場合の結合順に利用(大きいテーブルから先に) | 結合順の決定に利用。レンジの見積もりが最大インデックスダイブ数を超えた場合にも利用される | 述部の評価に利用。(利用可能なインデックスから何行マッチするかを推定)。population > 5000000がインデックスを使うべきでないかどうかを決めるのに利用する |
ありがとうございます。

表を出してみたのですが現状でも結構厳しいのでコンパクトに記載した現状維持とさせてください!原文忠実ですので読み取れない範囲でもないのではないかな、と思います。
<img width="568" alt="2017-03-20 17 20 11" src="https://cloud.githubusercontent.com/assets/1700792/24092456/bb4c03c2-0d91-11e7-99f1-b21603a96c8f.png">

2017-03-20 08:52 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include info.html info="統計を利用することで、品質見積もり時と商用環境で同じようにみえるクエリーが全く異なった実行となることがあります。クエリーの計画はデータ分布が変わるにつれて変化する可能性もあります" %}
比較対象が「環境」とそろっていないので「品質保証のための環境と本番環境で」とそろえてみます。ステージング環境、については少し広義な意味として利用され、「性能テスト」「クエリーチューニング」などを実施することが想像しにくくなるため前者のままとしたいと思います。

2017-03-20 08:53 UTC, takaidohigasi commented on _posts/2017-03-14-cost-based-optimization.md
> +{% include info.html info="統計を利用することで、品質見積もり時と商用環境で同じようにみえるクエリーが全く異なった実行となることがあります。クエリーの計画はデータ分布が変わるにつれて変化する可能性もあります" %}
ありがとうございます、修正します!

2017-03-20 08:58 UTC, takaidohigasi commented
コメントいただいた点、修正しました。

翻訳の抜け
https://github.com/yakst/unofficialmysqlguide-ja/pull/37/commits/18d0e6bef88dccac41b756b81917a62ce7d4023f

その他コメント
https://github.com/yakst/unofficialmysqlguide-ja/pull/37/commits/2848f264850395a2abf9d0bbee3434fc61f552f2

にて反映しております！

2017-03-20 13:18 UTC, doublemarket approved these changes

2017-03-22 20:59 UTC, merged