:books: translate chapter 8. hints
yakst/unofficialmysqlguide-ja pull request #38
Opened 2017-03-14 13:21 UTC by takaidohigasi

# 原文

http://www.unofficialmysqlguide.com/hints.html

2017-03-18 07:34 UTC, takaidohigasi commented
本人チェックOK

2017-03-18 10:32 UTC, doublemarket requested changes

2017-03-18 10:32 UTC, doublemarket commented on _posts/2017-03-14-hints.md
> +title: ヒント句
ヒント句ってOracle用語でしょうか？個人的な好みかもしれませんが、インデックスヒント、あるいはヒントの方がしっくりきます([MySQL 5.6のマニュアル](https://dev.mysql.com/doc/refman/5.6/ja/index-hints.html)にもインデックスヒント、ヒントは出てくるがヒント句はでてこない)。

2017-03-18 10:32 UTC, doublemarket commented on _posts/2017-03-14-hints.md
> +私はデバッグではヒント句をよく利用しますが、商用環境に導入するときにはいつも気をつけています。ヒント句はある時点で選択された特定の実行計画に固定するものであるため、データの分布やインデックスが時とともに変化した場合に維持管理上の重荷になりえます。
7章の訳で指摘したように、productionを本番と訳すならこれも合わせる必要がありますね。

2017-03-18 10:32 UTC, doublemarket commented on _posts/2017-03-14-hints.md
> +ベストプラクティスとしては、MySQLのメジャーバージョンアップグレードをした後(例えば、MySQL 9.0にアップグレードするときに)には毎回ヒント句を見直すと良いでしょう[^1]。新しい最適化が導入されると、それに伴いたくさんのヒントを無効化できることがお分かりになることでしょう。
英語のupgradeは日本語ではバージョンアップと言ってしまうことが多いと思うので、ここでは「MySQLのメジャーバージョンアップ」でもいいと思います。

2017-03-18 10:32 UTC, doublemarket commented on _posts/2017-03-14-hints.md
> +2. 「ヒント」であって命令型でないというとう明確なセマンティクスであること。すなわち、ヒントが実行できなかった場合、ステートメントは警告を発生させるもののエラーは発生させないということになります。これは`FORCE INDEX`などのヒントとは対照的で、この場合はインデックスが存在しないとエラーを発生させます。これは、例えばOracleデータベースのヒント句と似た挙動です。
命令形でないというとう → 命令形でないという

2017-03-18 10:32 UTC, doublemarket commented on _posts/2017-03-14-hints.md
> +2. 「ヒント」であって命令型でないというとう明確なセマンティクスであること。すなわち、ヒントが実行できなかった場合、ステートメントは警告を発生させるもののエラーは発生させないということになります。これは`FORCE INDEX`などのヒントとは対照的で、この場合はインデックスが存在しないとエラーを発生させます。これは、例えばOracleデータベースのヒント句と似た挙動です。
semanticsは単に「意味」の方が分かりやすいかもしれません。

2017-03-18 10:32 UTC, doublemarket commented on _posts/2017-03-14-hints.md
> +例6では、あるテーブルに対してrange最適化が無効化されています。これによりとても良い方法であるにも関わらず、p(population)インデックスが利用されません。population > 10億であるものはテーブル中に2行しかありません。
訳では英語の順と逆になっているのは日本語として自然なのでいいと思いますが、「これによりとても良い方法であるにも関わらず」よりも、「p(population)インデックスを使用した方がずっと良いにも関わらず、無視されてしまいます」とした方が「とても良い方法」とは何かが明確になって良いと思います。

2017-03-20 09:17 UTC, takaidohigasi commented on _posts/2017-03-14-hints.md
> +title: ヒント句
Oracle, PostgreSQL, MySQLでもいずれも利用する気がしたので確認しました
総称としては「ヒント」が正しそうですのでこれに修正します。

Oracle
https://docs.oracle.com/cd/E49329_01/server.121/b71278/sql_elements006.htm#i35922

PostgreSQL
※最も有名と思われるextention
http://pghintplan.osdn.jp/pg_hint_plan-ja.html

> ヒント句	実行計画を制御するための情報です。
> ヒント	実行計画を制御したいクエリに適用するヒント句を列挙したものです。

ヒントとヒント句は違う。

インデックスヒントはヒントの一部分で(SEMIJOINなどのヒントやQB_NAMEはこれには含まれない)、インデックスに対する機能を担うヒントの総称のようです。

2017-03-20 09:17 UTC, takaidohigasi commented on _posts/2017-03-14-hints.md
> +私はデバッグではヒント句をよく利用しますが、商用環境に導入するときにはいつも気をつけています。ヒント句はある時点で選択された特定の実行計画に固定するものであるため、データの分布やインデックスが時とともに変化した場合に維持管理上の重荷になりえます。
ありがとうございます、修正いたします！

2017-03-20 09:19 UTC, takaidohigasi commented on _posts/2017-03-14-hints.md
> +2. 「ヒント」であって命令型でないというとう明確なセマンティクスであること。すなわち、ヒントが実行できなかった場合、ステートメントは警告を発生させるもののエラーは発生させないということになります。これは`FORCE INDEX`などのヒントとは対照的で、この場合はインデックスが存在しないとエラーを発生させます。これは、例えばOracleデータベースのヒント句と似た挙動です。
ありがとうございます！

2017-03-20 09:37 UTC, takaidohigasi commented on _posts/2017-03-14-hints.md
> +2. 「ヒント」であって命令型でないというとう明確なセマンティクスであること。すなわち、ヒントが実行できなかった場合、ステートメントは警告を発生させるもののエラーは発生させないということになります。これは`FORCE INDEX`などのヒントとは対照的で、この場合はインデックスが存在しないとエラーを発生させます。これは、例えばOracleデータベースのヒント句と似た挙動です。
意味がわかりづらいのでちょっと見直してみました。

```
「ヒント」であって命令でないことを構造的に明確に示していること。
```

2017-03-20 09:39 UTC, takaidohigasi commented on _posts/2017-03-14-hints.md
> +例6では、あるテーブルに対してrange最適化が無効化されています。これによりとても良い方法であるにも関わらず、p(population)インデックスが利用されません。population > 10億であるものはテーブル中に2行しかありません。
ありがとうございます、コメントいただいたほうの役のほうが分かりやすいので修正します。
日本語力をあげなくては...

2017-03-20 09:50 UTC, takaidohigasi commented
ヒント句 → ヒントの修正については量が多いためコミットを分けました
https://github.com/yakst/unofficialmysqlguide-ja/pull/38/commits/dd87bce4ee642a15647b1fe360d0cc9a2e1fe4f6

その他の修正
https://github.com/yakst/unofficialmysqlguide-ja/pull/38/commits/58517ce8f4a18670621fff143c42f4adb36a0a5b

「コスト単位」 > 「コストユニット」の修正もついでにコミット積みました
https://github.com/yakst/unofficialmysqlguide-ja/pull/38/commits/9db20c8e86f974a33cce497652b6c794ced7e8c5

2017-03-22 13:14 UTC, doublemarket approved these changes
1点だけ指摘しましたがそれ以外はLGTM!

2017-03-22 13:14 UTC, doublemarket commented on _posts/2017-03-14-hints.md
> +1. どのように実行するかを教えるといったといったことは、SQLの宣言型の本質的なものと分離したほうが読みやすいし書きやすい
といった、が2回になっていますね。

2017-03-22 21:07 UTC, takaidohigasi commented on _posts/2017-03-14-hints.md
> +1. どのように実行するかを教えるといったといったことは、SQLの宣言型の本質的なものと分離したほうが読みやすいし書きやすい
ありがとうございます！読みかえしても気がつけませんでしたっ

2017-03-22 21:11 UTC, takaidohigasi commented on _posts/2017-03-14-hints.md
> +1. 「どのように実行するかを教える」といったことは、SQLの宣言型の本質的なものと分離したほうが読みやすいし書きやすい
といったの重複を修正しました

2017-03-26 23:12 UTC, merged