:books: translate chapter 10. Composite Indexes
yakst/unofficialmysqlguide-ja pull request #42
Opened 2017-04-08 06:04 UTC by takaidohigasi

## Issue

## 原文

10章 Composite Indexes
http://www.unofficialmysqlguide.com/composite-indexes.html

2017-04-08 06:22 UTC, takaidohigasi commented
久しぶりとりましたがコンテンツ追加しました...!

2017-04-08 06:35 UTC, takaidohigasi commented
次の章のCovering Indexsが「カバリングインデックス」としているところがなく、タイトルの整合性を少し検討中です。

A
* Composite Indexes
* Covering Indexes

B
* 複合インデックス
* カバリングインデックス

2017-04-08 06:39 UTC, takaidohigasi commented
「カバリングインデックス」の訳はまったくないわけではないようなのでいまのところ

* 複合インデックス
* カバリングインデックス

の予定

2017-04-08 11:36 UTC, doublemarket requested changes
細かいですがコメント

2017-04-08 11:36 UTC, doublemarket commented on _posts/2017-03-25-composite-indexes.md
> +アジア大陸のすべての国の人口が500万より多いわけではありませんので、2つの述部を合わせると「作業量を減らす」インデックスとなる可能性がでてきます。つまり、このデータセットでは複合インデックスにより選択性が改善するわけです。
助動詞はshouldなので、インデックスとなる可能性が出る、より、インデックスのはず、といったようにもう少し高い可能性を表してもいいかなと思います。

2017-04-08 11:36 UTC, doublemarket commented on _posts/2017-03-25-composite-indexes.md
> +4. **インデックスの順序(order)の変更に注意** : ASCあるいはDESCを混合すると、複合インデックスがいくつか利用されるか、に影響が発生する可能性があります。
いくつか利用されるか → いくつ利用されるか

2017-04-08 23:20 UTC, takaidohigasi commented on _posts/2017-03-25-composite-indexes.md
> +4. **インデックスの順序(order)の変更に注意** : ASCあるいはDESCを混合すると、複合インデックスがいくつか利用されるか、に影響が発生する可能性があります。
ありがとうございます、修正しました

2017-04-08 23:20 UTC, takaidohigasi commented on _posts/2017-03-25-composite-indexes.md
> +アジア大陸のすべての国の人口が500万より多いわけではありませんので、2つの述部を合わせると「作業量を減らす」インデックスとなる可能性がでてきます。つまり、このデータセットでは複合インデックスにより選択性が改善するわけです。
こちらも修正しました！

2017-04-12 09:18 UTC, takaidohigasi commented
こちらの記事修正いたしました！

2017-04-17 13:01 UTC, doublemarket approved these changes
👍 👍 👍

2017-04-23 22:12 UTC, merged