:books: translate chapter 11. Covering Indexes
yakst/unofficialmysqlguide-ja pull request #43
Opened 2017-04-08 11:10 UTC by takaidohigasi

2017-04-08 11:11 UTC, takaidohigasi commented on _posts/2017-04-08-covering-indexes.md
> +本番環境ではインデックスのクラスタリング効果によって、他のクエリーに比べメモリーをよりうまく使えるでしょう。アクセスされるセカンダリインデックスがクラスタインデックス(主キー)と「相関[^1]」がなかったらより多くのクラスタ化されたキーページへのアクセスが必要となるためです。
ここがちょっと自信なしです

2017-04-17 13:08 UTC, doublemarket requested changes

2017-04-17 13:08 UTC, doublemarket commented on _posts/2017-04-08-covering-indexes.md
> +`SELECT * FROM Country`以外で、`population > 5M and continent='Asia'`の条件を満たす国の名前のみが必要な場合を考えてみましょう。例12で示されるように、`c_p_n (Continent,Population,Name)`へのインデックスは、最初の2列を行を絞込むために、3つ目の列を値を返すために利用できます。
後半、「を」が連続してちょっと読みにくいので、例えば以下のようにしてみるのはどうでしょうか。

最初の2列は行を絞り込むために使用し、残りの3列目は値を返すために利用できます。

2017-04-17 13:08 UTC, doublemarket commented on _posts/2017-04-08-covering-indexes.md
> +カバリングインデックスが利用されたことが`EXPLAIN`の`"using_index": true`によって示されています。カバリングインデックスは正当に評価されない最適化の一つです。多くの方々が、カバリングインデックスではインデックスが利用される一方で、テーブルの行にアクセスしないため「コストが半分になる」と誤ってお考えです。例12では例11に示されるカバリングインデックスでないインデックス
誤ってお考えです、はちょっと他の部分と文体が合わない気がします。「間違って考えられています」ぐらいでどうでしょうか。

2017-04-17 13:08 UTC, doublemarket commented on _posts/2017-04-08-covering-indexes.md
> +[^1]: 相関というのは「だいたい同じ順序」ということを意図しています。例えば、セカンダリインデックスがtimestap型で挿入された場合、auto_incrementの主キーと高い相関があります。また、populationとcontinentへのインデックスは3文字の国コードである主キーと相関がありそうにありません。
timestap → timestamp

2017-04-17 13:08 UTC, doublemarket commented on _posts/2017-04-08-covering-indexes.md
> +[^1]: 相関というのは「だいたい同じ順序」ということを意図しています。例えば、セカンダリインデックスがtimestap型で挿入された場合、auto_incrementの主キーと高い相関があります。また、populationとcontinentへのインデックスは3文字の国コードである主キーと相関がありそうにありません。
「STAP細胞はあります」(言いたいだけ)

2017-04-23 00:11 UTC, takaidohigasi commented on _posts/2017-04-08-covering-indexes.md
> +`SELECT * FROM Country`以外で、`population > 5M and continent='Asia'`の条件を満たす国の名前のみが必要な場合を考えてみましょう。例12で示されるように、`c_p_n (Continent,Population,Name)`へのインデックスは、最初の2列を行を絞込むために、3つ目の列を値を返すために利用できます。
ありがとうございます、確かに読みづらいですね
修正します！

2017-04-23 00:20 UTC, takaidohigasi commented on _posts/2017-04-08-covering-indexes.md
> +カバリングインデックスが利用されたことが`EXPLAIN`の`"using_index": true`によって示されています。カバリングインデックスは正当に評価されない最適化の一つです。多くの方々が、カバリングインデックスではインデックスが利用される一方で、テーブルの行にアクセスしないため「コストが半分になる」と誤ってお考えです。例12では例11に示されるカバリングインデックスでないインデックス
ありがとうございます。

国語辞典でもいくつかしらべてみました。
「誤解されています」
としました。

2017-04-23 00:21 UTC, takaidohigasi commented on _posts/2017-04-08-covering-indexes.md
> +[^1]: 相関というのは「だいたい同じ順序」ということを意図しています。例えば、セカンダリインデックスがtimestap型で挿入された場合、auto_incrementの主キーと高い相関があります。また、populationとcontinentへのインデックスは3文字の国コードである主キーと相関がありそうにありません。
修正しましたっ

2017-04-23 11:26 UTC, doublemarket approved these changes

2017-04-23 22:13 UTC, merged