:books: translate chapter 12. Visual Explain
yakst/unofficialmysqlguide-ja pull request #44
Opened 2017-04-08 23:45 UTC by takaidohigasi

## 原文

http://www.unofficialmysqlguide.com/visual-explain.html

## Issue

2017-04-17 13:13 UTC, doublemarket requested changes

2017-04-17 13:13 UTC, doublemarket commented on _posts/2017-04-09-visual-explain.md
> +MySQL WorkbenchにはExplainが同梱されており、これは複雑な実行計画を人間が読みやすくするものです。内部的にはこの機能は`EXPLAIN FORMAT=JSON`を利用しているため、通常の`EXPLAIN FORMAT=JSON`以上の機能を「もたない」ことを述べておきます。実際のところ、シンプル化するためにカバリングインデックスの利用などのいくつかの出力を省略しています。
Explain → Visual Explain

補足も加えて「Visual Explainというツール」とした方がより親切かもしれません。

2017-04-17 13:13 UTC, doublemarket commented on _posts/2017-04-09-visual-explain.md
> +これまで例の中で見てきたように、選択性の高いrangeアクセスは選択性の低いrefアクセスより望ましく、これは小さなシンプル化かもしれません。
文脈からすると「a small simplification」は(オレンジなのにrangeの方が効率がいい場合だってあるのに！という)若干の批判的意味を込めて「これはおそらくちょっとした単純化でしょう」とかどうでしょうか。

2017-04-23 00:23 UTC, takaidohigasi commented on _posts/2017-04-09-visual-explain.md
> +MySQL WorkbenchにはExplainが同梱されており、これは複雑な実行計画を人間が読みやすくするものです。内部的にはこの機能は`EXPLAIN FORMAT=JSON`を利用しているため、通常の`EXPLAIN FORMAT=JSON`以上の機能を「もたない」ことを述べておきます。実際のところ、シンプル化するためにカバリングインデックスの利用などのいくつかの出力を省略しています。
欠けてしまいました... ありがとうございます。確かにわかりにくいので「Visual Explainというツール」にします

2017-04-23 00:29 UTC, takaidohigasi commented on _posts/2017-04-09-visual-explain.md
> +これまで例の中で見てきたように、選択性の高いrangeアクセスは選択性の低いrefアクセスより望ましく、これは小さなシンプル化かもしれません。
いいですね🎉 そちらになおしてみます

2017-04-23 11:27 UTC, doublemarket approved these changes

2017-04-23 22:14 UTC, merged