:books: translate chapter 13. Transient Plans
yakst/unofficialmysqlguide-ja pull request #45
Opened 2017-05-14 07:54 UTC by takaidohigasi

2017-05-14 07:57 UTC, takaidohigasi commented on _posts/2017-04-15-transient-plans.md
> +title: 一時的な実行計画
タイトルの訳が一番迷ってます。

* 「実行計画の移り変わり」
* 「実行計画の変化」
* 「一時的な実行計画」

など... 。意味的には「実行計画の移り変わり」としたいのですが

2017-05-15 11:50 UTC, doublemarket requested changes

2017-05-15 11:50 UTC, doublemarket commented on _posts/2017-04-15-transient-plans.md
> +同じようにみえるクエリーも全く違った実行計画となることがあります。これまでpopulationの述部を修正することによって確認してきました。例8では、population > `500M(5億)`を指定することで population >`5M(500万)`を指定した場合と異なったインデックスが選択されました。
細かいですが(5億)や(500万)はバッククオートの外に出した方がしっくりくる気がします。

2017-05-15 11:50 UTC, doublemarket commented on _posts/2017-04-15-transient-plans.md
> +* 数カ月分のデータに対して「昨日から現在まで」の範囲の日付を指定した場合、日付の列のインデックスが利用されるでしょう。一方で「昨年から現在まで」を指定した場合はインデックスは利用されないでしょう。
これもまたニュアンスの問題ですが、likelyは可能性が高い、may notはされないかもしれない、の方がより原著者の考える「起こりうる可能性」をよく表しているのではと思います。

2017-05-15 11:50 UTC, doublemarket commented on _posts/2017-04-15-transient-plans.md
> +これは予期された挙動で、統計収集(「メタデータと統計」の章で言及済み)の結果です。次の表は、*population*と*continent* が変わった際にインデックスの相対的コストがどの程度変化するかを示しています。
原文にもリンクはないですが、「メタデータと統計」にリンクを貼ってもいいのではないでしょうか(アンカーになっていなくて残念)。

https://yakst.github.io/unofficialmysqlguide-ja/cost-based-optimization.html

2017-05-15 11:50 UTC, doublemarket commented on _posts/2017-04-15-transient-plans.md
> +title: 一時的な実行計画
おっしゃる通り、移り変わるというニュアンスを出したいですね。うーん、すごい意訳というか付け足しちゃいますが「データによって移り変わる実行計画」とかだと、(原タイトルとは離れるけど)意味的にはしっくり来ますねえ。

2017-05-15 12:31 UTC, takaidohigasi commented on _posts/2017-04-15-transient-plans.md
> +同じようにみえるクエリーも全く違った実行計画となることがあります。これまでpopulationの述部を修正することによって確認してきました。例8では、population > `500M(5億)`を指定することで population >`5M(500万)`を指定した場合と異なったインデックスが選択されました。
ありがとうございます、修正します!

2017-05-15 12:35 UTC, takaidohigasi commented on _posts/2017-04-15-transient-plans.md
> +title: 一時的な実行計画
ご意見ありがとうございます！感謝！
感覚的に「データによって」が少し付け加えすぎな感覚があるので若干文字数を削って

変わりゆく実行計画(Transient Plans)

くらいにしようと思います

2017-05-15 12:35 UTC, takaidohigasi commented on _posts/2017-04-15-transient-plans.md
> +これは予期された挙動で、統計収集(「メタデータと統計」の章で言及済み)の結果です。次の表は、*population*と*continent* が変わった際にインデックスの相対的コストがどの程度変化するかを示しています。
ありがとうございます。確かに...。自分でも翻訳中に参考リンクを何回も探しました。

2017-05-15 12:43 UTC, takaidohigasi commented on _posts/2017-04-15-transient-plans.md
> +* 数カ月分のデータに対して「昨日から現在まで」の範囲の日付を指定した場合、日付の列のインデックスが利用されるでしょう。一方で「昨年から現在まで」を指定した場合はインデックスは利用されないでしょう。
ありがとうございます。

後者の訳文を下記としたいと思います。

一方で「昨年から現在まで」を指定した場合はインデックスは利用
`されないでしょう。` => `されないかもしれません。`

前者のlikelyを含む訳ですが「確からしさ」について明確にするように「おそらく」という訳をはさもうと思います。

2017-05-15 12:44 UTC, takaidohigasi commented on _posts/2017-04-15-transient-plans.md
> +* 数カ月分のデータに対して「昨日から現在まで」の範囲の日付を指定した場合、日付の列のインデックスが利用されるでしょう。一方で「昨年から現在まで」を指定した場合はインデックスは利用されないでしょう。
```
数カ月分のデータに対して「昨日から現在まで」の範囲の日付を指定した場合、日付の列のインデックスが利用されるでしょう。一方で「昨年から現在まで」を指定した場合はインデックスは利用されないでしょう。
```

```
数カ月分のデータに対して「昨日から現在まで」の範囲の日付を指定した場合は、おそらく日付の列のインデックスが利用されることでしょう。一方で「昨年から現在まで」を指定した場合はインデックスは利用されないかもしれません。
```

2017-05-15 12:54 UTC, takaidohigasi commented on _posts/2017-04-15-transient-plans.md
> +これは予期された挙動で、[統計収集(「メタデータと統計」の章で言及済み)](https://yakst.github.io/unofficialmysqlguide-ja/cost-based-optimization.html)の結果です。次の表は、*population*と*continent* が変わった際にインデックスの相対的コストがどの程度変化するかを示しています。
ページ全体へのリンクですが動作確認済み

2017-05-15 12:55 UTC, takaidohigasi commented
ありがとうございます。second commitでレビュー対応いたしました!

https://github.com/yakst/unofficialmysqlguide-ja/pull/45/commits/a2ca9c861aa7756db8707906296d93380d067a07

2017-05-15 13:29 UTC, doublemarket approved these changes

2017-05-16 22:48 UTC, merged