:books: translate chapter 13. Transient Plans
yakst/unofficialmysqlguide-ja pull request #46
Opened 2017-05-14 08:09 UTC by takaidohigasi

## Related Documents

https://dev.mysql.com/doc/refman/5.6/ja/subquery-optimization.html

## Original Article

http://www.unofficialmysqlguide.com/subqueries.html

## Issue

2017-05-15 12:30 UTC, takaidohigasi commented
難しくて苦戦中.

2017-05-15 13:03 UTC, takaidohigasi commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーは、サブクエリーがきっかり1行を返すもので、実行の際には最適化により除去しキャッシュすることが出来ます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています。
それぞれコストが1.00および4213.00

=> 下記のこと...?

"query_cost": "1.20"
"query_cost": "862.60"

2017-05-21 07:59 UTC, takaidohigasi commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーは、サブクエリーがきっかり1行を返すもので、実行の際には最適化により除去しキャッシュすることが出来ます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています。
それぞれコストが1.00および4213.00、まだ4213の正体が不明

=> 下記のこと...?

"query_cost": "1.20"
"query_cost": "862.60"

2017-05-23 00:06 UTC, doublemarket requested changes

2017-05-23 00:06 UTC, doublemarket commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーは、サブクエリーがきっかり1行を返すもので、実行の際には最適化により除去しキャッシュすることが出来ます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています。
optimize awayを日本語に訳す時は目的語を補わないとちょっと意味が分からなくなってしまうようです。要するに、結果として返す1行以外を最適化により除去する、ということだと思います。

2017-05-23 00:06 UTC, doublemarket commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーは、サブクエリーがきっかり1行を返すもので、実行の際には最適化により除去しキャッシュすることが出来ます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています。
どうみても1.20と862.60な気がしますね。。w
Morganさんに報告がてら「これどういう意味？」って聞いちゃうのもいいかもですね。

2017-05-23 00:06 UTC, doublemarket commented on _posts/2017-05-15-subqueries.md
> +このサブクエリーは少し効率的です。Countryテーブルに最初にアクセス(カバリングインデックスを利用し、インデックスオンリースキャンを利用)し、一致した各行に対して一連の行がCityテーブル内を`c(CountryCode)`インデックスを利用して参照されます。
毎度程度を表す副詞にばかり突っ込んで恐縮ですが、moderatelyは「少し」よりはましな(より程度の高い)ものを表していると思います。「まあまあ」とか「適度に」とかじゃないでしょうか。

2017-05-23 00:07 UTC, doublemarket commented
確かに日本語マニュアルは「実体化」と訳されていますが、Oracleではマテリアライズっていうのが一般的そうだし、「マテリアライズドビュー」とか一般的なので、materializeを実体化とするのは個人的には違和感が。。w (ただの独り言)

2017-05-23 15:17 UTC, takaidohigasi commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーは、サブクエリーがきっかり1行を返すもので、実行の際には最適化により除去しキャッシュすることが出来ます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています。
たしかにそうですね。一度状況報告がてら聞いてみます！

2017-05-23 15:45 UTC, takaidohigasi commented
> 確かに日本語マニュアルは「実体化」と訳されていますが、Oracleではマテリアライズっていうのが一般的そうだし、「マテリアライズドビュー」とか一般的なので、materializeを実体化とするのは個人的には違和感が。。w (ただの独り言)

「matelialized view」 → 「マテリアライズドビュー/マテリアライズド・ビュー」に関しては完全に同意です。
動詞としての使い方は確認できてません。該当マニュアルを確認するとうまく書いてあり判断つきかねました。現行ではこれを決断する基準がなく、最適化戦略としては実体化で個人的に内容理解できること、公式ドキュメントで過去に翻訳者が検討したであろう結論を尊重したいことから、公式ドキュメント訳にしたいと思ってます！

過去　関連ではMySQLの仮想生成列のエントリで少しディスカッションの上マテリアライズにしてました
https://yakst.com/ja/posts/3841

Oracle 
https://docs.oracle.com/cd/E57425_01/121/TDPPT/tdppt_sqlopt.htm#GUID-1E926221-441F-483A-B045-8AE4A5764B8C

2017-05-23 15:47 UTC, takaidohigasi commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーは、サブクエリーがきっかり1行を返すもので、実行の際には最適化により除去しキャッシュすることが出来ます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています。
> 目的語を補わないと

ありがとうございます。ご指摘のとおりですので補足します。

2017-05-23 15:47 UTC, takaidohigasi commented on _posts/2017-05-15-subqueries.md
> +このサブクエリーは少し効率的です。Countryテーブルに最初にアクセス(カバリングインデックスを利用し、インデックスオンリースキャンを利用)し、一致した各行に対して一連の行がCityテーブル内を`c(CountryCode)`インデックスを利用して参照されます。
ありがとうございます...!

2017-05-25 00:50 UTC, doublemarket commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーとは、サブクエリーのうちきっかり1行を返すもののことです。スカラーサブクエリーは、実行の最中に最適化により除去することができ、結果がキャッシュされます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています(
依然として読んだ人は「除去するって、何を除去するんだろう？」と考えるのではと思いますが、どうでしょうか。

2017-05-25 13:04 UTC, takaidohigasi commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーとは、サブクエリーのうちきっかり1行を返すもののことです。スカラーサブクエリーは、実行の最中に最適化により除去することができ、結果がキャッシュされます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています(
canをなくしてみると分かりやすいでしょうか。

スカラーサブクエリーは、実行の最中に最適化により除去され、結果がキャッシュされます。

2017-05-25 14:14 UTC, doublemarket commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーとは、サブクエリーのうちきっかり1行を返すもののことです。スカラーサブクエリーは、実行の最中に最適化により除去することができ、結果がキャッシュされます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています(
あれ、除去されるのはスカラーサブクエリー自身なんですか？下に出てくるJSONを見ても、スカラーサブクエリー(この例では`SELECT CountryCode FROM City WHERE name='Toronto'`)は無くなってはいないので、除去されてはいない気がしますが。。

optimize awayという句動詞の「away」を除去と訳すことにこだわると難しくなってしまう気がしますね。と思って検索して見たら、[同じようなことを考えている人が](http://qiita.com/7of9/items/5f87ec68a2f9d8bcde9a)。

例13ではスカラーサブクエリーが最適化されていない場合、例14では最適化された場合という対比があるので、awayを難しく考えず単に「最適化しきってしまう」ぐらいに訳し、かつcanを「できる」ではなく「可能性がある」という意味と捉えると、

スカラーサブクエリーとは、きっかり1行を返すサブクエリーのことで、実行時には最適化しきった上で結果がキャッシュできる可能性があります。

という感じだとどうでしょうか。これだと、例13と14にも話が繋がっていくんじゃないでしょうか。

2017-05-27 01:44 UTC, takaidohigasi commented on _posts/2017-05-15-subqueries.md
> +スカラーサブクエリーとは、サブクエリーのうちきっかり1行を返すもののことです。スカラーサブクエリーは、実行の最中に最適化により除去することができ、結果がキャッシュされます。例13で、Torontoの`CountryCode`を取得するスカラーサブクエリーの例を示しています。オプティマイザーがこれを2つのクエリーとみなしているのは重要で、それぞれコストが1.00および4213.00となっています(
ありがとうございます!
ここの章難しいですね... アドバイス助かります。

> スカラーサブクエリーとは、きっかり1行を返すサブクエリーのことで、実行時には最適化しきった上で結果がキャッシュできる可能性があります。

訳の結果、上記で同意です。修正してみます

canに関しては、ご指摘の通り13と14の差分を表すので残したほうがよさそうです。

Visual Explainの画像がoptimized_awayの結果をよく表しているので画像参照、の旨の訳注つけてみます。

http://www.unofficialmysqlguide.com/_images/explain-scalar.png

optimizer賢いですね...
```
show warnings;
/* select#1 */ select 'CAN' AS `Code`,'Canada' AS `Name`,'North America' AS `Continent`,'North America' AS `Region`,'9970610.00' AS `SurfaceArea`,'1867' AS `IndepYear`,'31147000' AS `Population`,'79.4' AS `LifeExpectancy`,'598862.00' AS `GNP`,'625626.00' AS `GNPOld`,'Canada' AS `LocalName`,'Constitutional Monarchy, Federation' AS `GovernmentForm`,'Elisabeth II' AS `HeadOfState`,'1822' AS `Capital`,'CA' AS `Code2` from `world`.`country` where 1
```

2017-05-27 04:58 UTC, takaidohigasi commented
画像参照の訳注はわかりづらいのでやめました!

2017-05-28 08:14 UTC, doublemarket approved these changes

2017-05-28 23:13 UTC, merged