:books: translate chapter 15. CTEs and VIEWs
yakst/unofficialmysqlguide-ja pull request #47
Opened 2017-05-21 09:11 UTC by takaidohigasi

2017-05-23 20:34 UTC, takaidohigasi commented
「論理変換」の章へのリンクを本文ではなくコメントで入れる予定
https://yakst.github.io/unofficialmysqlguide-ja/logical-transformation.html

2017-05-24 10:40 UTC, doublemarket commented
@takaidohigasi これって私がAssigneeになっていますけど、Reviewerのことでしょうか？

2017-05-25 13:00 UTC, takaidohigasi commented
申し訳ございません、、、操作誤りです、レビューいただけますでしょうか！

2017-05-25 13:59 UTC, doublemarket requested changes

2017-05-25 13:59 UTC, doublemarket commented on _posts/2017-05-21-ctes-and-views.md
> +2. **実体化** : 共通テーブル式またはビューを実行しその結果を一時テーブルに保存します。残りのクエリーは一時テーブルに対して実行されます。実体化は一般的には遅い手法であり、マージの手法が適さないと判断されたときに選択されます。早期に実体化することで工程が短縮され実行が高速化する可能性があり、このときは上記の例外となります。
原文を読まないと、「この時は上記の例外となります」の「この時」はどの時なのか？という疑問が生まれてしまう気がします。原文を読んでみると、実体化は本来なら遅いけれども早めに実体化すると工程全体が短くなって高速化する時もあってそういうのは例外的です、ということだと思うので、例えば原文を尊重して

これには例外があり、早期に実体化することで工程が短縮され実行が高速化するという場合があてはまります。

とかどうでしょうか。

2017-05-27 05:03 UTC, takaidohigasi commented on _posts/2017-05-21-ctes-and-views.md
> +2. **実体化** : 共通テーブル式またはビューを実行しその結果を一時テーブルに保存します。残りのクエリーは一時テーブルに対して実行されます。実体化は一般的には遅い手法であり、マージの手法が適さないと判断されたときに選択されます。早期に実体化することで工程が短縮され実行が高速化する可能性があり、このときは上記の例外となります。
ありがとうございます。
ここの訳はとても悩んでおります。

前の文が

```
実体化は一般的には遅い手法であり、マージの手法が適さないと判断されたときに選択されます。
```

選択される、まで記載されているので、「これには例外があり」と続けたときに少し混乱招くと考え語順を変更していました。

ご指摘もっともで再度考えてみたら「これには例外があり」の「これ」を不明確なことがやはり原因なので、指示語を利用せずに内容を再記するようにしてみます

2017-05-27 05:06 UTC, takaidohigasi commented on _posts/2017-05-21-ctes-and-views.md
> +2. **実体化** : 共通テーブル式またはビューを実行しその結果を一時テーブルに保存します。残りのクエリーは一時テーブルに対して実行されます。実体化は一般的には遅い手法であり、マージの手法が適さないと判断されたときに選択されます。早期に実体化することで工程が短縮され実行が高速化する可能性があり、このときは上記の例外となります。
> The materialize option is usually the slower method, and chosen when the merge option is not suitable. There are exceptions to this, where early materialization can shortcut work and lead to faster execution.

2017-05-27 05:14 UTC, takaidohigasi commented on _posts/2017-05-21-ctes-and-views.md
> +2. **実体化** : 共通テーブル式またはビューを実行しその結果を一時テーブルに保存します。残りのクエリーは一時テーブルに対して実行されます。実体化は一般的には遅い手法であり、マージの手法が適さないと判断されたときに選択されます。早期に実体化することで工程が短縮され実行が高速化する可能性があり、このときは上記の例外となります。
1. 実体化の方が高速になる例外的なケースとして、...
2. 語順はやはり原文を尊重した語順とします

とし

実体化の方が高速になる例外的なケースとして、早期に実体化することで工程が短縮され実行が高速化するというケースがあります。

としてみます！

2017-05-28 08:16 UTC, doublemarket approved these changes
改訂後のでとても分かりやすくなったと思います！

2017-05-28 11:15 UTC, takaidohigasi commented
ありがとうございます!

2017-05-28 23:13 UTC, merged