:books: translate chapter 17. Aggregation
yakst/unofficialmysqlguide-ja pull request #49
Opened 2017-06-25 07:10 UTC by takaidohigasi

2017-06-26 13:45 UTC, doublemarket requested changes

2017-06-26 13:45 UTC, doublemarket commented on _posts/2017-06-25-aggregation.md
> +1. **ルースインデックススキャン**: `GROUP BY`条件にインデックスが付与されていれば、MySQLはインデックスを最初から最後までスキャンすることを選択し、中間的な結果の実体化を回避します。この操作は述部の選択性が非常に高く、作成される一時テーブルが非常に大きい、というわけではない場合には良い選択となります。
ルース → ルーズ？(図のキャプションも同じ)

2017-06-26 13:45 UTC, doublemarket commented on _posts/2017-06-25-aggregation.md
> +1. **ルースインデックススキャン**: `GROUP BY`条件にインデックスが付与されていれば、MySQLはインデックスを最初から最後までスキャンすることを選択し、中間的な結果の実体化を回避します。この操作は述部の選択性が非常に高く、作成される一時テーブルが非常に大きい、というわけではない場合には良い選択となります。
「非常に大きい」と「というわけではない」の間に点が入ってしまうと、大きいと言い切ってしまう印象が強くなってわかりにくくなってしまうので、入れない方がいいと思います。

2017-06-26 13:45 UTC, doublemarket commented on _posts/2017-06-25-aggregation.md
> +3. **行の抽出とソートの両方**: この最適化はインデックスを利用し行を抽出した結果が`GROUP BY`操作における正しい順序となっている場合にこの最適化が適用されます。
主語である「この最適化」が2回出てきているので、どちらか消した方がいいです。

2017-06-26 13:45 UTC, doublemarket commented on _posts/2017-06-25-aggregation.md
> +2. **行の抽出**: インデックスは対象行があるかどうかを判別するのに利用され、その結果は一時テーブルに保存されます。結果は一時テーブルに集約され、デフォルトでは`GROUP BY`条件によってソートされます。[^1]
細かいですが、2文目の「一時テーブルに集約され」は「その一時テーブル(上)で集約され」とした方が、より前の文との繋がりがはっきりしていいと思いました。

2017-06-26 14:14 UTC, takaidohigasi commented on _posts/2017-06-25-aggregation.md
> +1. **ルースインデックススキャン**: `GROUP BY`条件にインデックスが付与されていれば、MySQLはインデックスを最初から最後までスキャンすることを選択し、中間的な結果の実体化を回避します。この操作は述部の選択性が非常に高く、作成される一時テーブルが非常に大きい、というわけではない場合には良い選択となります。
> 「非常に大きい」と「というわけではない」の間に点が入ってしまうと、大きいと言い切ってしまう印象が強くなってわかりにくくなってしまうので、入れない方がいいと思います。

たしかにご指摘のとおりです...!

ルースインデックススキャンについては公式ドキュメントの日本語訳をお借りしました、これを対訳に書くべきでしたごめんなさい...!初めて聞いたワードなので既存のものでよいかな、と思ってます
https://dev.mysql.com/doc/refman/5.6/ja/group-by-optimization.html

2017-06-26 14:15 UTC, takaidohigasi commented on _posts/2017-06-25-aggregation.md
> +2. **行の抽出**: インデックスは対象行があるかどうかを判別するのに利用され、その結果は一時テーブルに保存されます。結果は一時テーブルに集約され、デフォルトでは`GROUP BY`条件によってソートされます。[^1]
ありがとうございます、、、いつも自分で読みかえして気が付かないところをありがとうございます！

2017-06-26 14:16 UTC, takaidohigasi commented on _posts/2017-06-25-aggregation.md
> +3. **行の抽出とソートの両方**: この最適化はインデックスを利用し行を抽出した結果が`GROUP BY`操作における正しい順序となっている場合にこの最適化が適用されます。
最初の部分を削除します... これは完全に日本語おかしいですね...!ありがとうございます。

2017-06-26 14:58 UTC, takaidohigasi commented on _posts/2017-06-25-aggregation.md
> +1. **ルースインデックススキャン**: `GROUP BY`条件にインデックスが付与されていれば、MySQLはインデックスを最初から最後までスキャンすることを選択し、中間的な結果の実体化を回避します。この操作は述部の選択性が非常に高く、作成される一時テーブルが非常に大きい、というわけではない場合には良い選択となります。
というわけではない、がかかる部分が直前だけでないことを明示するために点をつけようとしてました。
とは言えわかりづらいので下記のようにしてみます

この操作は「述部の選択性が非常に高く、作成される一時テーブルが非常に大きい」というわけではない

2017-06-27 02:36 UTC, doublemarket approved these changes
👍 👍 👍

2017-06-28 21:37 UTC, takaidohigasi commented
ありがとうございます

2017-06-28 21:37 UTC, merged