:books: translate chapter 18. Sorting
yakst/unofficialmysqlguide-ja pull request #50
Opened 2017-07-02 08:15 UTC by takaidohigasi

2017-07-02 08:24 UTC, takaidohigasi commented
レビューお願いします...!

2017-07-02 11:44 UTC, doublemarket requested changes
えいっ！

2017-07-02 11:44 UTC, doublemarket commented on _posts/2017-07-01-sorting.md
> +MySQLには結果をソートされた順序で*返す*4つの方法があり、これは`ORDER BY`または`GROUP BY`(`ORDER BY NULL`を除く)で必要となります。`EXPLAIN`はソート操作が必要かどうかを表示しますが、どのソートアルゴリズムが利用されるかは表示**しません**。この情報は`OPTIMIZER_TRACE`によって取得できます。結果をソートするのに利用される4つの手
こまかいかもですが、「これは〜で必要となります」は「これらは〜が必要とします」の方が

- 4つ方法があるのでそれを受けて複数形
- 必要とするのはORDER BYとGROUP BYであることが明確

なのでよいと思いました。

2017-07-02 11:44 UTC, doublemarket commented on _posts/2017-07-01-sorting.md
> +```sql
このコードブロックを4つ(2つでもいける？)スペースでインデントすると、順序付きリストの中の要素になります。

2017-07-02 11:44 UTC, doublemarket commented on _posts/2017-07-01-sorting.md
> +このクエリーはテーブルスキャンとなり、人口の多い10行をバッファーに持つことになります。新しくより人口の多い行が見つかれば、以前の行が優先度つきキューから押しだされます。
これも4つインデントしないと、次の3.以降が順序付きリストになりません(GitHub上では表示が崩れてます)。

2017-07-02 11:44 UTC, doublemarket commented on _posts/2017-07-01-sorting.md
> +1. **インデックスを利用** :  B+ツリーインデックスをはソート順に保たれるため、いくつかの`ORDER BY`クエリーは全くソートする必要がありません。
someはここでは個数(いくつか)を表しているのではなく、「そういう場合もある」(fewでもmost ofでもなく、かつa fewよりは少し頻度が高いぐらい？)という程度を表していると思うので、「全くソートする必要がない`ORDER BY`も存在します」的なのでどうでしょうか。

2017-07-02 11:44 UTC, doublemarket commented on _posts/2017-07-01-sorting.md
> +    4. 一時ファイルをマージソートした後、行をソート順に並び替え、ソートされたタプルから必要な行を直接読み取ります。
「ソート順に並べ替え」は若干違和感があるのですが(並べ替え順に並べ替える、は当たり前だから)、「by sort key value」をそのまま訳して「ソートキーの値の順に並べ替え」ではどうでしょうか。

2017-07-02 13:13 UTC, takaidohigasi commented on _posts/2017-07-01-sorting.md
> +MySQLには結果をソートされた順序で*返す*4つの方法があり、これは`ORDER BY`または`GROUP BY`(`ORDER BY NULL`を除く)で必要となります。`EXPLAIN`はソート操作が必要かどうかを表示しますが、どのソートアルゴリズムが利用されるかは表示**しません**。この情報は`OPTIMIZER_TRACE`によって取得できます。結果をソートするのに利用される4つの手
ありがとうございます。

複数 => 修正します
主体を明らかにする => もう少し考えてみます

`sorting is required` ですので受け身にしてみます。

2017-07-02 13:13 UTC, takaidohigasi commented on _posts/2017-07-01-sorting.md
> +```sql
ありがとうございます! 修正します! (下のインデントも修正します、ありがとうございます

2017-07-02 13:14 UTC, takaidohigasi commented on _posts/2017-07-01-sorting.md
> +    4. 一時ファイルをマージソートした後、行をソート順に並び替え、ソートされたタプルから必要な行を直接読み取ります。
ご指摘のとおりですね... 修正してみます!

2017-07-02 13:22 UTC, takaidohigasi commented
修正部分の表示
<img width="927" alt="2017-07-02 22 21 50" src="https://user-images.githubusercontent.com/1700792/27770178-f330d422-5f74-11e7-84ad-b0d6efbcb9b6.png">

2017-07-02 13:29 UTC, takaidohigasi commented
詳細なレビューありがとうございます、何度か推敲して修正してみました!

2017-07-03 01:02 UTC, doublemarket approved these changes
細かい誤字の指摘をしましたが、それ以外はlooks good to meおーいぇー

2017-07-03 01:02 UTC, doublemarket commented on _posts/2017-07-01-sorting.md
> +1. **インデックスを利用** : B+ツリーインデックスをはソート順に保たれるため、`ORDER BY`クエリーの中には全くソートする必要がないケースがあります。
をは -> は

をっは〜！(言いたいだけ)

2017-07-03 01:02 UTC, doublemarket commented on _posts/2017-07-01-sorting.md
> +    2. 各行について、ある値のペア(ソートキーの値と行ID)かるなる値で構成されるタプルをソートバッファーに保存します。
かるなる -> からなる

2017-07-03 06:38 UTC, takaidohigasi commented on _posts/2017-07-01-sorting.md
> +1. **インデックスを利用** : B+ツリーインデックスをはソート順に保たれるため、`ORDER BY`クエリーの中には全くソートする必要がないケースがあります。
ぉはぁ.....

2017-07-03 06:40 UTC, takaidohigasi commented
修正しました!! リリースしますっ

2017-07-03 06:41 UTC, merged