:books: translate chapter 19. Partitioning
yakst/unofficialmysqlguide-ja pull request #51
Opened 2017-07-02 10:57 UTC by takaidohigasi

## Original Article

http://www.unofficialmysqlguide.com/partitioning.html

## Issues

https://github.com/yakst/unofficialmysqlguide-ja/issues/19

## Related Documents

パーティションプルーニング(5.6 ja)
https://dev.mysql.com/doc/refman/5.6/ja/partitioning-pruning.html

パーティション化
https://dev.mysql.com/doc/refman/5.6/ja/partitioning.html

## 主な対訳

partitioning: パーティショニング
partition pruning: パーティションプルーニング

※Oracle Databaseではパーティション・プルーニングでしたがMySQL公式はパーティションプルーニングのようなのでそちらを尊重

2017-07-02 11:02 UTC, takaidohigasi commented on _posts/2017-07-03-partitioning.md
> +* **マルチバージョンスキームが適用されたスキーマ[^1]**:  アプリケーションによってはデータを決して削除せず、古い世代の行を履歴を残す目的で保存するポリシーをとるものがあります。例えばあるユーザーの住所を更新するとき、全ての以前の住所を保持する場合です。住所が古く無効なものかどうかでパーティショニングするとメモリーを効率的に利用できます。
Multi-versioned schema => 悩んだ末「マルチバージョンスキームが適用されたスキーマ」

ご意見募集してます

2017-07-02 11:03 UTC, takaidohigasi commented on _posts/2017-07-03-partitioning.md
> +* **ローカリティーがある**: 例えば、パーティションがstore\_id(店舗ID)あるいは地域で作成される場合です。
この辺のタイトル軒並み結構まよいました...

2017-07-02 11:09 UTC, takaidohigasi commented on _posts/2017-07-03-partitioning.md
> +* **論理削除(soft delete)**: 多くのアプリケーションは論理削除を実装しており(例: is\_deleted)、削除済みあるいは削除されていないデータのみによくアクセスします。
不可視インデックスのところにもsoft deleteという単語が利用され日本ではこの概念が「論理削除」と呼ばれることがおおいもののlogical/physicalではなく、概念としてsoft/hardでちょこっと違うので日本語訳どうしたらよいか迷います
http://www.unofficialmysqlguide.com/invisible-indexes.html

2017-07-02 11:11 UTC, takaidohigasi commented on _posts/2017-07-03-partitioning.md
> +* **論理削除(soft delete)**: 多くのアプリケーションは論理削除を実装しており(例: is\_deleted)、削除済みあるいは削除されていないデータのみによくアクセスします。
a) `ソフトデリート`とする
b) 論理削除とする
c) その他

2017-07-02 11:58 UTC, doublemarket requested changes
ほいさ

2017-07-02 11:58 UTC, doublemarket commented on _posts/2017-07-03-partitioning.md
> +* **論理削除(soft delete)**: 多くのアプリケーションは論理削除を実装しており(例: is\_deleted)、削除済みあるいは削除されていないデータのみによくアクセスします。
説明や例のカラム名から言ってどう考えても論理削除なので、あえてソフトデリートとカタカナを当てず一般的に使われている論理削除でいいと思います！
(ソフトデリートなんて言うんだ、と思って検索してみたらLaravelのドキュメントはカタカナを当ててるようでたくさん出てきますねw)

2017-07-02 11:58 UTC, doublemarket commented on _posts/2017-07-03-partitioning.md
> +* **ローカリティーがある**: 例えば、パーティションがstore\_id(店舗ID)あるいは地域で作成される場合です。
localityは個人的には「局所性」と訳すなーと思ったら、Wikipediaにページがありました https://ja.wikipedia.org/wiki/%E5%8F%82%E7%85%A7%E3%81%AE%E5%B1%80%E6%89%80%E6%80%A7

2017-07-02 11:58 UTC, doublemarket commented on _posts/2017-07-03-partitioning.md
> +* **ローカリティーがある**: 例えば、パーティションがstore\_id(店舗ID)あるいは地域で作成される場合です。
細かいですが、リストのタイトルは全部体言止めにするとか全部「ある」で終わらせるとか、統一した方がきれいかなと思います。

2017-07-02 13:32 UTC, takaidohigasi commented on _posts/2017-07-03-partitioning.md
> +* **論理削除(soft delete)**: 多くのアプリケーションは論理削除を実装しており(例: is\_deleted)、削除済みあるいは削除されていないデータのみによくアクセスします。
ありがとうございます。

`ソフトデリート` => これは見たことないのですが... (orz) それに一致する翻訳がない場合カタカナ化して原文の意味を損なわず固有名詞化/普及させてしまおうという戦略でした。

2017-07-02 13:32 UTC, takaidohigasi commented on _posts/2017-07-03-partitioning.md
> +* **ローカリティーがある**: 例えば、パーティションがstore\_id(店舗ID)あるいは地域で作成される場合です。
ありがとうございます! そちらに修正します

2017-07-03 01:04 UTC, doublemarket approved these changes
👍

2017-07-03 06:42 UTC, takaidohigasi commented
こちらもありがとうございます!

2017-07-03 06:43 UTC, merged